### PR TITLE
refactor: migrate to ES6

### PR DESCRIPTION
**Pull request by SukkaW**
### `Notable Changes`

Migrate to ES6.

https://github.com/posthtml/posthtml/blob/acc430df7353cfe31e173ce43f28af6ce79941ff/package.json#L22-L24

PostHTML is always dropping old Node.js version even it is still compatible. So why don't we embrace the new JavaScript syntax?

The migration for the unit test will be updated in another PR.

#### `Commit Message Summary (CHANGELOG)`

```
refactor: migrate to ES6
```

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply and delete all others_

- [ ] CI
- [ ] Fix
- [ ] Perf
- [ ] Docs
- [ ] Test
- [ ] Chore
- [ ] Style
- [ ] Build
- [ ] Feature
- [x] Refactor

### `SemVer`

> ℹ️  What changes to the current `semver` range does your PR introduce?

> 👉  _Put an `x` in the boxes that apply and delete all others_

- [ ] Fix (:label: Patch)
- [ ] Feature (:label: Minor)
- [ ] Breaking Change (:label: Major)

No API changes, no bugs fixed. However, the PR should be considered as a refactoring.

### `Checklist`

> ℹ️  You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is a reminder of what we are going to look for before merging your code.

> 👉  _Put an `x` in the boxes that apply and delete all others._

- [x] Lint and unit tests pass with my changes
- [ ] I have added tests that prove my fix is effective/works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes are merged and published in downstream modules

### CODE REVIEW

**Comment by SukkaW** [comment]
FYI, most of the migration is done by [lebab](https://github.com/lebab/lebab).

**Comment by anikethsaha** [comment]
how about ESM build with transpiled to es5 and cjs for non-supported environments?

cc @Scrum

**Comment by Scrum** [comment]
@anikethsaha So far, there is no special need for this, but I am considering the option of migrating to `TypeScript`

**Comment by anikethsaha** [comment]
yes there is no much requirement for these. Just thought

**Comment by SukkaW** [comment]
> how about ESM build with transpiling to es5 and cjs for non-supported environments?

The approach has been used at `htmlnano`: Code is written in ES Module, while transpile to Node.js compatible CommonJS ES5 when publishing on npm.

Since ES Module is still a `Stability: 1 - Experimental` feature for Node.js, IMHO ES Module should only be used during development.

Also, +1 for TypeScript.

**Review by anikethsaha — APPROVED** [review]

**Review by Scrum — APPROVED** [review]

**Pull request merged**
