### PR TITLE
fix(*): Cannot read property 'length' of undefined

### PR DESCRIPTION
**Pull request by GitScrum**

### CODE REVIEW

**Comment by GitScrum** [comment]
@posthtml/collaborators

**Comment by GitScrum** [comment]
@voischev thanks !

**Comment by GitScrum** [comment]
@mrmlnc ping

**Comment by mrmlnc** [comment]
If I fully understand this case, then maybe `[].concat(plugins)`?

**Comment by GitScrum** [comment]
@mrmlnc approve ?

**Comment by GitScrum** [comment]
@mrmlnc approve ?

**Comment by mrmlnc** [comment]
@GitScrum, yeap!

**Comment by GitScrum** [comment]
@mrmlnc thanks. @voischev merge ?

**Comment by GitScrum** [comment]
@mrmlnc thanks. @voischev merge ?

**Pull request merged**
