### PR TITLE
make parser configurable

### LINKED ISSUE #137: parser: option
[PostCSS] has a `parser:` option to choose a different parser to generate the AST ([LESS], [Sass], or _[SugarSS]_ for example) for the rest of the plugins to work on.

Shouldn't PostHTML have the equivalent option to generate it's _PostHTMLTree_?

Then you could use _any_ tempting engine as input.

[Pug][pug] ([formerly Jade][jade]) for example would be something like…
```js
pug = require('pug')
plugins = [
  require('posthtml-plugin')
  require('posthtml-plugin')
]
options =
  //sync: true
  parser: pug

posthtml(plugins)
  .process(html, options)
  .then(function(result) {
    console.log(result.html);
  });
```

I know there is currently [posthtml-jade], but it doesn't work quite as smoothly as it might if there was a _proper_ way of doing this… plus this would add support for other template engines, present and future.

[postcss]: https://github.com/postcss/postcss/blob/master/docs/api.md#processor-class
[pug]: https://github.com/pugjs/pug
[jade]: http://jade-lang.com
[posthtml-jade]: https://github.com/michael-ciniawsky/posthtml-jade
[sass]: https://github.com/postcss/postcss-scss
[less]: https://github.com/gilt/postcss-less
[sugarss]: https://github.com/postcss/sugarss

### PR DESCRIPTION
**Pull request by jescalan**
This would fix #137

I don't have a test written for this yet, because I'd need to write a little parser for the test, and want to make sure people are on board with this first. If they are, I'll write one.

Before making this happen, want to make sure that you guys are confident in the parser you are currently using, and that the API for `posthtml-parser` is fairly solid. Once this is done, next step seems to be documenting the parser's expected output so that people are able to write/add custom parsers.

### CODE REVIEW

**Comment by awinogradov** [comment]
Hey @jescalan! Thank you for your PR. It's cool work, but where you find the reason to use this solution instead of this https://github.com/posthtml/posthtml/issues/137#issuecomment-221108337 ? Can you explain the benefits?

**Comment by jescalan** [comment]
@awinogradov definitely. you can see a couple oddities produced by this method in posthtml-jade specifically here: https://github.com/posthtml/posthtml-jade#caveats

Basically the issue is that if there is a fragment of html anywhere in the parsed language, even if it is part of a code example in an article etc, it will parse it and cause an error. There are also issues with using html strings as locals/expressions this way.

Another issue is speed. Passing it all the way through the html parser, when you have every intent of not having it parsed for html at all is time wasted. If you know you are parsing a different language that is not html, there's no reason to pass it through the html parser first.

This approach is faster, cleaner, and less likely to produce bugs for custom parsers. It's also a super simple implementation, so it adds little to no overhead. 👍

**Comment by jescalan** [comment]
Hey there!

Just want to mention that I have built a whitespace-based html parser that exports a posthtml AST. I tested it out with the fork that was used to make this PR, and it's working quite well with posthtml.

https://github.com/static-dev/html-whitespace-parser

There's an example in the readme that shows how to configure it with posthtml, and example input and output.

Real world use case 😁

**Comment by voischev** [comment]
Fix Travis Errors plz

**Comment by voischev** [comment]
first commit message shown to format https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit plz. Needful for automake changelog.md file https://github.com/posthtml/posthtml/blob/master/.mversionrc

**Comment by michael-ciniawsky** [comment]
feat(): make parser configurable,
fix(): missing semicolon

and 👍 for sugarml

**Comment by jescalan** [comment]
You can format it like this when you merge. Just click the dropdown arrow on the button and select "squash and merge", then you can enter the commit message 😁

**Comment by michael-ciniawsky** [comment]
@voischev will be minor release? asking in terms of build/middleware updates comming now

**Comment by voischev** [comment]
minor yes

**Comment by voischev** [comment]
merge in https://github.com/posthtml/posthtml/commit/bfa3e6de0ca96d52a8a1110433e1c5b52fc44aa1

**Comment by jescalan** [comment]
Want me to to run a release for this?

**Pull request closed without merging**
