### PR TITLE
add posthtml-px2rem

### PR DESCRIPTION
**Pull request by hzlzh**

### CODE REVIEW

**Comment by TrySound** [comment]
@voischev posthtml - inline css processor. Really?

**Comment by voischev** [comment]
Why not?

**Comment by voischev** [comment]
Alternative posthtml-postcss + postcss plugins ;)

**Comment by TrySound** [comment]
@voischev I'm for that. We need one or a few entry points like posthtml-postcss or posthtml-inline-styles which will pass css in callback. But posthtml plugins for this purpose is wrong way for ecosystem.

**Comment by voischev** [comment]
@TrySound write about in https://github.com/weixin/posthtml-px2rem/issues/3 issue

**Comment by hzlzh** [comment]
@TrySound Task blow is some of our project's `Gulp Workflow`
We'd like to get `px-to-rem` ready when `moveHtml` (form `src` to `dist`) run, so I add this posthtml plugin to do that.

```
// Build dist 流程
gulp.task('build', gulp.series(
    reset,
    compileLessBuild,
    replaceCSS,
    compileAutoprefixer,
    renameCSS,
    miniCSS,
    gulp.parallel(
        moveHtml,
        imageminImg,
        imageminSprite,
        uglifyJs
    )
));


function moveHtml() {
    return gulp.src(paths.src.html, {base: paths.src.dir})
        .pipe(posthtml(posthtmlPx2rem({rootValue: 20, minPixelValue: 2})))
        .pipe(gulp.dest(paths.dist.dir));
}
```

**Comment by TrySound** [comment]
@hzlzh But was about posthtml->postcss->px-to-rem chain? Postcss for styles. Posthtml for markup.

**Pull request merged**
