### PR TITLE
Enable "should.eventually" assertions

### PR DESCRIPTION
**Pull request by maltsev**
All `should.eventually` assertions weren't tested as there were no returns. I enabled them. So now there are 2 failed tests.

### CODE REVIEW

**Comment by zxqfox** [comment]
Nice catch! Thanks.

Can you please try to fix these lines?
https://github.com/maltsev/posthtml/commit/ac437b76d2b228ecc2134bb34c3a2c58033378fe#diff-84ae455cd06132c67c64f28d46136d46R140

**Comment by zxqfox** [comment]
Btw, maybe we can just use this package https://www.npmjs.com/package/ispromise

https://github.com/then/is-promise/commits/master/index.js

**Comment by maltsev** [comment]
@zxqfox, thanks for the advice! I'll try to fix that tomorrow (if no one else does that before).

**Comment by zxqfox** [comment]
```
$ node -p "p = new (require('vow').Promise); typeof p === 'function' && p.then && p.catch"
false
```
Yeah, there it is. /cc @voischev

**Comment by maltsev** [comment]
This PR could be closed. I've fixed the promise check in another PR: #113

**Pull request closed without merging**
