### PR TITLE
changed README to add link to grunt-posthtml

### PR DESCRIPTION
**Pull request by TCotton**
Added link to grunt-posthtml

### CODE REVIEW

**Comment by voischev** [comment]
You can write a text block like [Gulp plugin for PostHTML](https://github.com/posthtml/posthtml#gulp-plugin-for-posthtml)?

**Comment by TCotton** [comment]
There you go Ivan. I've added a more detailed Grunt description matching the Gulp documentation

**Comment by TCotton** [comment]
Ivan, I'm wring a blog article on PostHTML. Who started this project off, was it yourself and Anton Winogradov?

**Comment by voischev** [comment]
All team http://theprotein.io ;)

**Comment by voischev** [comment]
Anton create a first commit, yes

**Comment by TCotton** [comment]
are you based in Russia?

**Comment by voischev** [comment]
@TCotton yes. form Moscow

**Pull request merged**
