### PR TITLE
README updates

### LINKED ISSUE #117: Create PostHTML Wiki
I currently update the README and personally think it is quite a big bunch already on the way to become confusing. Separate wiki pages would give the different sections and usecases a better structure to find what people need and provide room for in-depth explanations e.g (write a plugin, middleware..). 

As i'm in the process already i would make a start, are there any concerns/arguments against creating a wiki?

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
resolve #117

### CODE REVIEW

**Comment by voischev** [comment]
Squach commints?
change commit message on the mask `feat(docs): message text`

example commit message
`feat(docs): update Readme & create docs/ folder`

plz

**Comment by michael-ciniawsky** [comment]
Should it be named ---->feat<----?(docs): update README, add docs folder?

**Comment by voischev** [comment]
use https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#type for https://github.com/posthtml/posthtml/blob/master/.mversionrc#L5

**Comment by voischev** [comment]
done?

**Comment by michael-ciniawsky** [comment]
yes but this gives my a headache [master](https://github.com/michael-ciniawsky/posthtml/commits/master) plz take a look at the commits.Why is there xyz commited with michael-ciniawsky, this commits where part of the rebase, but i'm not sure if something went wrong during rebasing or if i need to rebase this in a different way :)

**Comment by voischev** [comment]
ok. I'm fix this.

**Comment by michael-ciniawsky** [comment]
thank you :+1:

**Pull request merged**
